config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :recipes
  resources :recipe_steps, only: [], param: :index do
    member do
      delete '(:id)' => 'recipe_steps#destroy', as: ''
      post '/' => 'recipe_steps#create'
    end
  end
  resources :recipe_ingredients, only: [], param: :index do
    member do
      delete '(:id)' => 'recipe_ingredients#destroy', as: ''
      post '/' => 'recipe_ingredients#create'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/recipe_step.rb
# frozen_string_literal: true

# This is the model is used to describe the different steps required
# to prepare a recipe. Each RecipeStep belongs to a specific Recipe.
# Example: step 1: cut the onions, step 2: fry the onions, etc.
class RecipeStep < ApplicationRecord
  belongs_to :recipe, optional: true
  before_validation :set_step_number, on: :create

  def set_step_number
    self.step_number = recipe.recipe_steps.count + 1
  end
end

app/controllers/recipe_steps_controller.rb
# frozen_string_literal: true

class RecipeStepsController < ApplicationController
  before_action :setup_recipe

  def new; end

  def destroy; end

  private

  def setup_recipe
    @recipe = Recipe.new(recipe_steps: [RecipeStep.new])
  end
end

app/views/recipe_steps/_form.html.erb
<%= turbo_frame_tag "recipe_step_#{form.index}" do %>
  <%= form.hidden_field :id %>

  <div>
    <%#= form.label :etape, style: "display: block" %>
    <%= form.text_area:instructions, placeholder: "Mélanger les oeufs et le sucre" %>
  </div>

  <%= form.submit "Supprimer l'étape", formaction: recipe_step_path(form.index, form.object.id),
                                  formmethod: :delete,
                                  formnovalidate: true,
                                  data: { turbo_frame: "recipe_step_#{form.index}" } %>
<% end %>

app/views/recipe_steps/_recipe_step.html.erb
<div id="<%= dom_id recipe_step %>">
  <p>
    <strong>Étape <%= recipe_step.step_number %> :</strong><br />
    <%= recipe_step.instructions %>
  </p>

  <p>
    <%= button_to 'Edit', edit_recipe_step_path(recipe_step), method: :post %>
    <%= button_to 'Delete', recipe_step, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
</div>

app/views/recipe_steps/create.turbo_stream.erb
<%= fields model: @recipe do |form| %>
  <%= form.fields_for :recipe_steps, child_index: params[:index] do |recipe_step_form| %>
    <%= turbo_stream.replace "add-recipe_step" do %>
      <%= form.submit "Ajouter une étape",
            formaction: recipe_step_path(recipe_step_form.index.to_i + 1),
            formmethod: :post,
            formnovalidate: true,
            id: "add-recipe_step" %>
    <% end %>

    <%= turbo_stream.append "recipe_steps" do %>
      <%= render "form", form: recipe_step_form %>
    <% end %>
  <% end %>
<% end %>

app/views/recipe_steps/destroy.html.erb
<%= fields model: @recipe do |form| %>
  <%= form.fields_for :recipe_steps, child_index: params[:index] do |recipe_step_form| %>
    <%= turbo_frame_tag "recipe_step_#{recipe_step_form.index}" do %>
      <%= recipe_step_form.hidden_field :id, value: params[:id] %>
      <%= recipe_step_form.hidden_field :_destroy, value: true %>
    <% end %>
  <% end %>
<% end %>

app/views/recipe_steps/edit.html.erb
<h1>Editing recipe step</h1>

<%= render "form", recipe_step: @recipe_step %>

<br>

<div>
  <%= link_to "Show this recipe step", @recipe_step %> |
  <%= link_to "Back to recipe steps", recipe_steps_path %>
</div>

app/views/recipe_steps/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Recipe steps</h1>

<div id="recipe_steps">
  <% @recipe_steps.each do |recipe_step| %>
    <%= render recipe_step %>
  <% end %>
</div>

<div id="new_recipe_step">
  <%= render partial: "recipe_steps/form", locals: { recipe_step: RecipeStep.new } %>
</div>

app/views/recipe_steps/new.html.erb
<h1>New recipe step</h1>

<%= render "form", recipe_step: @recipe_step %>

<br>

<div>
  <%= link_to "Back to recipe steps", recipe_steps_path %>
</div>