config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :recipes
  resources :recipe_steps, only: [], param: :index do
    member do
      delete '(:id)' => 'recipe_steps#destroy', as: ''
      post '/' => 'recipe_steps#create'
    end
  end
  resources :recipe_ingredients, only: [], param: :index do
    member do
      delete '(:id)' => 'recipe_ingredients#destroy', as: ''
      post '/' => 'recipe_ingredients#create'
    end
  end

  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/recipe.rb
# frozen_string_literal: true

# The Recipe model encapsulates the details of a cooking recipe. It belongs to a User
# (the creator of the recipe) and a RecipeCategory. It also has many ingredients
# through the RecipeIngredient association, and it can be commented on and rated by Users.
class Recipe < ApplicationRecord
  belongs_to :user
  belongs_to :recipe_category
  has_many :recipe_ingredients, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :recipe_utensils
  has_many :utensils, through: :recipe_utensils
  has_many :recipe_steps, dependent: :destroy
  has_one_attached :image

  validates :title, presence: true
  validates :cooking_time, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :servings, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :difficulty, inclusion: { in: ['Très Facile', 'Facile', 'Moyen', 'Difficile'] }

  # before_save :calculate_total_time

  enum status: { initial_draft: 0, published: 1, archived: 2, private_status: 3 }, _prefix: :status

  accepts_nested_attributes_for :recipe_steps, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :recipe_ingredients, reject_if: :all_blank, allow_destroy: true
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  def show
    @recipe = Recipe.find(params[:id])
    @recipe_steps = @recipe.recipe_steps
    @servings = @recipe.servings
    @cooking_time = @recipe.cooking_time
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new(recipe_steps: [RecipeStep.new], recipe_ingredients: [RecipeIngredient.new])
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes
  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /recipes/1
  def update
    if @recipe.update(recipe_params)
      redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /recipes/1
  def destroy
    @recipe.destroy!

    redirect_to recipes_url, notice: 'Recipe was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:title, :servings, :cooking_time, :recipe_category_id, :difficulty, :description,
                                   :image, recipe_steps_attributes: %i[id instructions],
                                           recipe_ingredients_attributes: %i[id name quantity unit ingredient_id _destroy])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titre, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description,
                        placeholder: "Racontez nous l'histoire de cette recette. Qu'est-ce ou qui vous a inspiré pour la cuisiner ? Qu'est-ce qui la rend spécial pour vous ?", rows: 4 %>
  </div>

  <%= render "image_preview", form: form, recipe: recipe %>

  <div>
    <%= form.label :catégorie_de_recette, style: "display: block" %>
    <%= form.select :recipe_category_id, RecipeCategory.all.map { |c| [c.name, c.id] } %>
  </div>

  <div>
    <%= form.label :portions, style: "display: block" %>
    <%= form.number_field :servings %>
  </div>

  <div>
    <%= form.label :cooking_time, "Temps de préparation (minutes)" , style: "display: block" %>
    <%= form.number_field :cooking_time %>
  </div>

  <div>
    <%= form.label :difficulté, style: "display: block" %>
    <%= form.select :difficulty, ["Très Facile", "Facile", "Moyen", "Difficile"] %>
  </div>

  <h4>Ingrédients</h4>
  <div id="recipe_ingredients">
    <%= form.fields_for :recipe_ingredients do |recipe_ingredient_form| %>
      <%= render "recipe_ingredients/form", form: recipe_ingredient_form %>
    <% end %>
  </div>

  <%= form.submit "Ajoute un ingrédient", formaction: recipe_ingredient_path(@recipe.recipe_ingredients.size),
                                      formmethod: :post,
                                      formnovalidate: true,
                                      id: "add-recipe_ingredient" %>

  <h4>Création d'étapes</h4>
  <div id="recipe_steps">
    <%= form.fields_for :recipe_steps do |recipe_step_form| %>
      <%= render "recipe_steps/form", form: recipe_step_form %>
    <% end %>
  </div>

  <%= form.submit "Ajoute une étape", formaction: recipe_step_path(@recipe.recipe_steps.size),
                                      formmethod: :post,
                                      formnovalidate: true,
                                      id: "add-recipe_step" %>

  <div>
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/recipes/_image_preview.html.erb
<div data-controller="previews">
  <%= form.label :image, style: "display: block" %>
  <%= form.file_field :image,
    direct_upload: true,
    data: { previews_target: "input", action: "change->previews#preview" } %>

    <% if recipe.image.attached? %>
      <%= image_tag recipe.image, data: { previews_target: "preview" }, class: "img-responsive" %>
    <% else %>
      <%= image_tag "", data: { previews_target: "preview" }, class: "img-responsive" %>
    <% end %>
</div>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Nom:</strong><br />
    <%= recipe.title %>
  </p>

  <% if recipe.description.present? %>
    <p>
      <strong>Description:</strong><br />
      <%= recipe.description %>
    </p>
  <% end %>

  <%= image_tag(recipe.image, class: "img-responsive") if recipe.image.attached? %>
</div>

app/views/recipes/edit.html.erb
<h1>Modifier la recette</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Voir la recette", @recipe %> |
  <%= link_to "Retour à l'accueil", recipes_path %>
</div>

app/views/recipes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mes Recettes</h1>

<div id="recipes">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Voir la recette", recipe %>
    </p>
  <% end %>
</div>

<%= link_to "Nouvelle recette", new_recipe_path %>
<%= link_to "Retour à l'acceuil", root_path %>

app/views/recipes/new.html.erb
<h1>Nouvelle recette</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Retour à l'accueil", root_path %>
</div>

app/views/recipes/show.html.erb
<p style="color: green"><%= notice %></p>

<p>
  <%= "Catégorie : #{@recipe.recipe_category.name}" %> |
  <%= "Difficulté : #{@recipe.difficulty}" %> |
  <%= "Préparation : #{pluralize(@cooking_time, 'minute')}" %>
</p>

<%= render @recipe %>

<p>
  <%= "Pour #{pluralize(@servings, 'personne')}" %>
</p>

<h4>Ingrédients</h4>
<p>
  <% @recipe.recipe_ingredients.each do |recipe_ingredient| %>
    <%= recipe_ingredient.quantity %>
    <%= recipe_ingredient.unit %>
    <%= recipe_ingredient.name %><br />
  <% end %>
</p>

<!-- TODO:  Render the ustensils -->

<% @recipe.recipe_steps.each_with_index do |step, index| %>
  <p>
    <strong>Étape <%= index + 1 %> :</strong><br />
    <%= step.instructions %>
  </p>
<% end %>

<div>
  <%= link_to "Modifier la recette", edit_recipe_path(@recipe) %> |
  <%= link_to "Retour à l'accueil", recipes_path %>

  <%= button_to "Supprimer la recette", @recipe, method: :delete %>
</div>